### ISSUE TITLE
Carousel elements are not rendered by position

### ISSUE THREAD

**Issue by loevgaard** [Setono/SyliusCmsPlugin#89]
I have this carousel:

![image](https://user-images.githubusercontent.com/2412177/148778732-64934e54-f6c1-442b-958f-ac5de04f28c5.png)

but in the frontend:

![image](https://user-images.githubusercontent.com/2412177/148778831-dce596d7-6e74-44d7-ba27-d7821ac4465a.png)

it still starts off by showing slide 1

**Comment by psihius** [comment]
@loevgaard took a peek at this one and it's not a bug - it's just cache.
Do the `rm -Rf tests/Application/var/cache/test/pools/*` and it works. 
You have the order by automatically applied to the relation for the blocks on the Carousel entity definition
```
        <one-to-many field="carouselBlocks" target-entity="Setono\SyliusCMSPlugin\Model\CarouselBlockInterface"
                     mapped-by="carousel" orphan-removal="true">
            <!-- There is an issue with fetch eager and orderBy: https://github.com/doctrine/orm/issues/4256 -->
            <cascade>
                <cascade-all/>
            </cascade>
            <order-by>
                <order-by-field name="position" direction="ASC" />
            </order-by>
        </one-to-many>
```
And as far as I can tell, blocks are grabbed via the relation and not via a Repository method. That happens at `src/Renderer/CarouselRenderer.php:70`

**Comment by psihius** [comment]
In this case, we would need to invalidate the cache for it to re-render the template again. I see you have a `CachedViewRenderer` that does that and sets a cache. `ElementCacheKeyGenerator` has quite a few keys in there, including per locale generation.
I could add a listener on the entities (this has to be done probably for everything that is cached) so it invalidates specific keys. Or we could just invalidate the whole pool, BUT invalidating the whole pool on a bigger store setup is probably a bad idea cause it will cause huge performance degradation and would likely overload the servers.

So it's either a bit complex but smarter solution, or an easy and dumb one.

**Comment by psihius** [comment]
This is actually referenced by #88
